import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';

const root = process.cwd();
const output = join(root, 'out');
const site = JSON.parse(readFileSync('content/generated/site.json', 'utf8'));
const home = JSON.parse(readFileSync('content/generated/home.json', 'utf8'));
const pages = JSON.parse(readFileSync('content/generated/pages.json', 'utf8'));
const expectedSlugs = ['', 'codes', 'beginner-guide', 'how-to-steal-eggs', 'all-animals', 'tier-list', 'value-list'];
const origin = 'https://stealanimalegg.github.io';
const failures = [];
const checks = (condition, message) => { if (!condition) failures.push(message); };
checks(site.readyForLaunch || process.argv.includes('--prelaunch'), 'Launch gate is off. Set readyForLaunch only after QA, or use --prelaunch while editing.');
const read = path => existsSync(path) ? readFileSync(path, 'utf8') : '';
const decode = s => s.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#x27;|&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&nbsp;/g, ' ');
const textOnly = html => decode(html.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, '').replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ').trim();
const attrs = tag => Object.fromEntries([...tag.matchAll(/([\w:-]+)="([^"]*)"/g)].map(m => [m[1], decode(m[2])]));
const meta = (html, name) => [...html.matchAll(/<meta\b[^>]*>/g)].map(m => attrs(m[0])).filter(a => a.name === name || a.property === name).map(a => a.content);
const url = slug => `${origin}/${slug ? `${slug}/` : ''}`;
const walk = dir => existsSync(dir) ? readdirSync(dir).flatMap(n => {const f=join(dir,n);return statSync(f).isDirectory()?walk(f):[f];}) : [];
checks(pages.length === 6 && pages.every(p => p.enabled), 'Exactly six enabled core pages are required.');
checks(expectedSlugs.slice(1).every(s => pages.some(p => p.slug === s)), 'The locked page set has changed.');
const rows = [];
const seenTitles = new Set();
const seenDescriptions = new Set();
// Add exceptions only after confirming a name in an official source for this game.
const additionalOfficialAnimals = [];
const animalExamples = [
  ['Cat', 'Common', '$3/s'],
  ['Geek Cat', 'Divine', '$847Q/s'],
];
for (const slug of expectedSlugs) {
  const definition = slug ? pages.find(p => p.slug === slug) : home;
  const html = read(join(output, slug, 'index.html'));
  checks(!!html, `Missing static page: /${slug}/`);
  const title = decode(html.match(/<title>([\s\S]*?)<\/title>/)?.[1] || '');
  const descriptions = meta(html, 'description');
  const h1 = [...html.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/g)].map(m => textOnly(m[1]));
  const canonical = [...html.matchAll(/<link\b[^>]*>/g)].map(m => attrs(m[0])).filter(a => a.rel === 'canonical').map(a => a.href);
  checks(title === definition?.title && title.length <= 60, `${slug || '/'}: title must match the blueprint and be <=60 characters.`);
  checks(!seenTitles.has(title), `${slug}: duplicate title.`);seenTitles.add(title);
  checks(descriptions.length === 1 && descriptions[0] === definition?.description && descriptions[0].length <= 160, `${slug}: invalid description.`);
  checks(!seenDescriptions.has(descriptions[0]), `${slug}: duplicate description.`);seenDescriptions.add(descriptions[0]);
  checks(h1.length === 1 && h1[0] === definition?.hero.heading, `${slug}: exactly one matching H1 is required.`);
  checks(canonical.length === 1 && canonical[0] === url(slug), `${slug}: incorrect canonical.`);
  const robot = meta(html, 'robots').join(' ');
  checks(site.readyForLaunch ? /\bindex\b/.test(robot) && /\bfollow\b/.test(robot) && !/noindex|nofollow/.test(robot) : /noindex/.test(robot), `${slug}: incorrect indexing state.`);
  checks(meta(html, 'og:title')[0] === title && meta(html, 'og:description')[0] === descriptions[0] && meta(html, 'og:url')[0] === url(slug), `${slug}: incorrect Open Graph metadata.`);
  const main = html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/)?.[1] || '';
  const article = main.match(/<article class="guide-article">([\s\S]*)<\/article>/)?.[1] || main;
  const visible = textOnly(article);
  const words = visible.match(/[a-z0-9]+(?:['-][a-z0-9]+)*/gi)?.length || 0;
  // Homepage includes its useful hero answer, without counting navigation or footer.
  const hero = !slug ? textOnly(main.split('<div class="guide-content-grid">')[0]) : '';
  const mainWords = words + (hero.match(/[a-z0-9]+(?:['-][a-z0-9]+)*/gi)?.length || 0);
  checks(mainWords >= (slug ? 800 : 1200), `${slug}: insufficient visible content (${mainWords} words).`);
  checks(!/coming soon|\bTODO\b|placeholder|will be published|could not verify|insufficient evidence|research pipeline|according to the prompt|generated by|SEO audit/i.test(visible), `${slug}: unfinished or internal copy.`);
  if (['all-animals', 'tier-list', 'value-list'].includes(slug)) {
    const firstTable = article.match(/<table\b[^>]*>[\s\S]*?<\/table>/)?.[0] || '';
    const tableRows = [...firstTable.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/g)]
      .map(m => [...m[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/g)].map(cell => textOnly(cell[1])))
      .filter(row => row.length);
    checks(animalExamples.every(example => tableRows.some(row => example.every((cell, i) => row[i] === cell))), `${slug}: public animal examples must lead the first table.`);
    checks(article.includes('href="https://www.roblox.com/games/99679692310083/Steal-Animal-Egg"'), `${slug}: official source link missing.`);
  }
  if (slug === 'all-animals') {
    checks([...article.matchAll(/<h2\b[^>]*>([\s\S]*?)<\/h2>/g)].some(m => textOnly(m[1]) === 'Steal Animal Egg Animals Reference'), 'Animal reference heading missing.');
    const wrongAnimals = ['Dragon', 'Tiger', 'Eagle', 'Wolf', 'Chicken'].filter(name => !additionalOfficialAnimals.includes(name));
    checks(!wrongAnimals.length || !new RegExp(`\\b(?:${wrongAnimals.join('|')})\\b`, 'i').test(visible), 'Animal reference contains a wrong-game animal.');
    checks(!/carry speed|nest defense|rare egg hatch odds/i.test(visible), 'Animal reference contains an unsupported system.');
  }
  if (slug === 'tier-list') {
    checks(!/defense stats?|carry capacity|nest defense|1,?000x baseline|100x baseline/i.test(visible), 'Tier list contains unsupported ranking stats.');
    const tierRows = definition.sections.flatMap(s => s.table?.rows ?? []);
    checks(['S', 'A', 'B', 'C', 'D'].every(t => tierRows.some(r => r[0] === t)), 'Editorial S–D ranking guide is missing.');
  }
  if (slug === 'value-list') {
    checks(/displayed\s+(?:pet\s+)?income/i.test(visible) && /progression/i.test(visible)
      && /(?:rather than|instead of|separate from).{0,80}(?:trade|market)/i.test(visible), 'Value list must explain its income/progression scope.');
    checks(!definition.sections.some(s => s.table?.columns.some(c => /trade price|market price|trading value/i.test(c))), 'Value list contains a speculative market-price table.');
    checks(!/(?:trade|trading|market)\s+price\s*(?:is|:|=)?\s*\$\d/i.test(visible), 'Value list contains an unsupported trading price.');
  }
  for (const s of expectedSlugs.slice(1)) {
    const path = `/${s}/`;
    const header = html.match(/<header\b[\s\S]*?<\/header>/)?.[0] || '';
    const footer = html.match(/<footer\b[\s\S]*?<\/footer>/)?.[0] || '';
    checks(header.includes(`href="${path}"`) && footer.includes(`href="${path}"`), `${slug}: navigation missing ${path}.`);
  }
  const related = definition?.relatedSlugs || [];
  checks(related.every(s => article.includes(`href="/${s}/"`)), `${slug}: missing contextual related links.`);
  if (!slug) checks(expectedSlugs.slice(1).every(s => article.includes(`href="/${s}/"`)), 'Homepage must contextually link to all six pages.');
  for (const m of html.matchAll(/<a\b[^>]*>/g)) {
    const href = attrs(m[0]).href;
    if (href?.startsWith('#')) { checks(html.includes(`id="${href.slice(1)}"`), `${slug}: broken section link ${href}.`); continue; }
    if (!href || !href.startsWith('/') || href.startsWith('//')) continue;
    const pathname = href.split(/[?#]/)[0];
    const file = resolve(output, `.${pathname}`);
    checks(file.startsWith(`${output}/`) || file === output, `${slug}: unsafe internal path.`);
    checks(existsSync(file.endsWith('/') || !/\.[a-z0-9]+$/i.test(pathname) ? join(file, 'index.html') : file), `${slug}: broken internal link ${href}.`);
  }
  for (const m of html.matchAll(/<img\b[^>]*>/g)) {
    const a = attrs(m[0]);
    checks('alt' in a, `${slug}: image lacks alt.`);
    checks(a.src?.startsWith('/') && existsSync(join(output,a.src)), `${slug}: broken or remote image ${a.src}.`);
  }
  const schemas = [...html.matchAll(/<script\b[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)].flatMap(m => {try {const parsed=JSON.parse(m[1]);return Array.isArray(parsed)?parsed:parsed['@graph']||[parsed];} catch {failures.push(`${slug}: invalid JSON-LD`);return [];}});
  const types = schemas.map(s => s['@type']);
  for (const type of slug ? ['WebPage','BreadcrumbList','FAQPage'] : ['WebSite','VideoGame','FAQPage']) checks(types.includes(type), `${slug}: missing ${type} schema.`);
  if (definition?.pageType === 'guide') checks(types.includes('HowTo'), `${slug}: missing HowTo schema.`);
  checks(!types.some(t => ['Review','AggregateRating','Offer','Product','ItemList'].includes(t)), `${slug}: unsupported schema.`);
  checks(schemas.filter(s=>s['@type']==='FAQPage').every(s=>s.mainEntity?.length), `${slug}: empty FAQ schema.`);
  checks(schemas.filter(s=>s['@type']==='FAQPage').every(s=>s.mainEntity.length===definition?.faq.length), `${slug}: FAQ schema and visible content differ.`);
  rows.push({path:slug?`/${slug}/`:'/',title,description:descriptions[0],h1:h1[0],words:mainWords,canonical:canonical[0],schema:types.join(', ')});
}
const codes=JSON.parse(read('content/generated/codes.json'));
const launchCodes = [
  ['HASHTAGS', 'x5 Cash Potion', 'working'],
  ['1MVISITS', '1 Fanxys Egg', 'working'],
  ['ENDGAME', '10 minutes of income', 'working'],
  ['DEMONIC', '10 minutes of income', 'working'],
  ['RANDOMBAT', 'Random Bait', 'expired'],
];
for (const [code, reward, status] of launchCodes) {
  checks(codes.entries.some(entry => entry.code === code && entry.reward === reward && entry.status === status), `Current code data regressed: ${code}.`);
}
for(const code of codes.entries) {
  checks(textOnly(read(join(output,'codes/index.html'))).includes(`${code.code} ${code.reward} ${code.status === 'working' ? 'Working' : 'Expired'}`), `Code missing or mismatched: ${code.code}.`);
  if(code.status==='working') checks(textOnly(read(join(output,'index.html'))).includes(`${code.code} ${code.reward} Working`), `Homepage code mismatch: ${code.code}.`);
}
const legalSlugs = ['about','contact','privacy','terms','copyright'];
for (const slug of legalSlugs) {
  const html=read(join(output,slug,'index.html'));
  checks(!!html && meta(html,'robots').some(v=>v.includes('noindex')), `${slug}: legal page must exist and be noindex.`);
  checks(read(join(output,'index.html')).includes(`href="/${slug}/"`), `${slug}: legal footer link missing.`);
}
checks(meta(read(join(output,'404.html')),'robots').some(v=>v.includes('noindex')), '404 must be noindex.');
const sitemap = read(join(output,'sitemap.xml'));
const locations=[...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>decode(m[1]));
checks(locations.length===7 && expectedSlugs.every(s=>locations.includes(url(s))), 'Sitemap must contain exactly the seven launch URLs.');
const robots=read(join(output,'robots.txt'));
checks(site.readyForLaunch ? robots.includes('Allow: /') && !robots.includes('Disallow: /') : robots.includes('Disallow: /'), 'Robots does not match launch state.');
checks(site.hosting.siteUrl===origin, 'The locked domain changed.');
checks(read('content/generated/integrations.json').includes('G-Y2WWS8HF0V'), 'GA4 configuration is missing.');
checks([...walk(join(output,'_next')).filter(f=>f.endsWith('.js')), join(output,'index.html')].some(f=>read(f).includes('G-Y2WWS8HF0V')), 'GA4 is missing from the built JavaScript.');
const manifest=JSON.parse(read(join(output,'manifest.webmanifest'))||'{}');
checks(manifest.icons?.every(i=>i.type==='image/webp' && existsSync(join(output,i.src))), 'Manifest icon is invalid.');
checks(existsSync(join(output,site.assets.openGraph)), 'OG image does not exist.');
checks(existsSync(join(output,site.assets.cover)), 'Configured banner image does not exist.');
checks(read(join(output,'index.html')).includes(`src="${site.assets.cover}"`), 'Configured banner is missing from the homepage.');
const forbidden = new RegExp(['Yori'+'ch','Fact'+' Pack','Evidence'+' IDs?','Co'+'dex','Clau'+'de','Chat'+'GPT',"Drag(?:n|N)?['’]?\\s*Wash","Drag['’]n Wash",'Gator'+' Dragon Games','zelda'+'dungeon','local'+'host','waiting to be added to the content registry','will be published here','Generated by '+'AI','AI '+'generated','SEO '+'audit','raw '+'prompt','coming '+'soon','\\bTO'+'DO\\b'].join('|'),'i');
const secret = /(?:AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9]{30,}|sk-[A-Za-z0-9_-]{32,}|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----)/;
const sources=['app','components','config','content','lib','public/images','scripts','.github'].flatMap(walk).concat(['README.md','next.config.ts','package.json']).filter(f=>/\.(tsx?|json|svg|css|mjs|md|yml)$/.test(f) && !f.endsWith('seo-qa.mjs'));
const exported=walk(output).filter(f=>/\.(html|txt|xml|json|webmanifest|svg)$/.test(f) && !f.includes('/_next/'));
for(const f of [...sources,...exported]) {
  const contents=read(f);
  checks(!forbidden.test(contents), `Forbidden residue in ${f.replace(root+'/','')}.`);
  checks(!secret.test(contents), `Credential-like literal in ${f.replace(root+'/','')}.`);
  checks(!/\/Users\/|\/home\/[a-z]+\/|file:\/\//i.test(contents), `Local filesystem path in ${f.replace(root+'/','')}.`);
}
console.table(rows.map(r=>({page:r.path,titleChars:r.title.length,descriptionChars:r.description.length,H1:1,words:r.words})));
console.log(`Sitemap: ${locations.length} URLs; launch state: ${site.readyForLaunch}; inspected ${sources.length} source and ${exported.length} exported files.`);
if (failures.length) {console.error([...new Set(failures)].join('\n'));process.exitCode=1;}
else console.log(`SEO QA passed for all seven launch pages${site.readyForLaunch?' (index, follow)':' (prelaunch noindex)'}, legal pages, schemas, links, assets, and residue scan.`);
